### PR TITLE
add condition to travis.yml to build only if commit is tagged

### PR DESCRIPTION
**Pull request by kudukacar**

### CODE REVIEW

**Comment by damonkelley** [comment]
**suggestion**: I think it would be ideal if the build always runs, but only *deploys* when there is a tag.

We want the rest of the build to always run so that we know our project compiles and the tests are passing. This is the essence  [Continuous Integration](https://www.martinfowler.com/articles/continuousIntegration.html).

There are [mechanisms that are already built in](https://docs.travis-ci.com/user/customizing-the-build#skipping-a-build) that allow us to skip a build if that is desirable. For example, you probably don't need to run your tests if your commit only updates the README it would be reasonable to skip such a commit.

**Comment by damonkelley** [comment]
Additionally, since we are going to change that behavior, it is probably a good idea to include information in the README on how to tag if that is ultimately what triggers the deploy. Are there project conventions on what a tag should look like? etc.

**Comment by kudukacar** [comment]
Sounds good.  I'll adjust the travis configuration and update the README.

**Review by damonkelley — APPROVED** [review]
🎉

**Pull request merged**
